# Generated by Django 4.2.7 on 2024-02-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerComponents', '0003_order_orderproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
