# Generated by Django 4.2.7 on 2024-02-28 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ComputerComponents', '0004_rename_adress_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_ru', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField()),
                ('delivery_closing_date', models.DateTimeField()),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerComponents.order')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerComponents.deliverystatus')),
            ],
        ),
    ]
