# Generated by Django 4.2.7 on 2024-02-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerComponents', '0005_deliverystatus_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='id_order_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ComputerComponents.orderproducts'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
