# Generated by Django 4.2.7 on 2024-02-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerComponents', '0006_delivery_id_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id_order_products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ComputerComponents.orderproducts'),
            preserve_default=False,
        ),
    ]
