# Generated by Django 4.2.7 on 2024-02-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerComponents', '0007_alter_delivery_id_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_stock',
            name='count_product',
            field=models.PositiveIntegerField(),
        ),
    ]
